import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { mockFiles, mockInsights } from '@/lib/mockData';
import { BarChart2, AlertTriangle, MessageSquare } from 'lucide-react';

const insightIconMap = {
  summary: <BarChart2 className='w-5 h-5 text-blue-500' />,
  risk: <AlertTriangle className='w-5 h-5 text-red-500' />,
  recommendation: <MessageSquare className='w-5 h-5 text-green-500' />,
  data: <BarChart2 className='w-5 h-5 text-yellow-500' />,
};

export default function DocumentDetail() {
    const file = mockFiles[0];
    const insights = mockInsights.filter(i => i.fileId === file.id);

  return (
    <div>
        <h1 className='text-xl font-semibold md:text-2xl mb-4'>Document Details: {file.name}</h1>
        <div className='grid gap-8 grid-cols-1 md:grid-cols-2'>
            <div>
                <Card>
                    <CardHeader>
                        <CardTitle>Document Preview</CardTitle>
                        <CardDescription>This is a placeholder for the document viewer.</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <div className='bg-muted aspect-video w-full flex items-center justify-center rounded-md'>
                            <p className='text-muted-foreground'>Document Preview Area</p>
                        </div>
                    </CardContent>
                </Card>
            </div>
            <div>
                <Card>
                    <CardHeader>
                        <CardTitle>AI Insights</CardTitle>
                         <CardDescription>Insights generated by SomaScribe AI.</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <div className='space-y-4'>
                        {insights.map(insight => (
                            <div key={insight.id} className='flex items-start gap-3 p-2 rounded-lg hover:bg-muted'>
                                {insightIconMap[insight.type as keyof typeof insightIconMap]}
                                <div>
                                    <p className='font-medium'>{insight.title}</p>
                                    <p className='text-sm text-muted-foreground'>{insight.description}</p>
                                </div>
                            </div>
                        ))}
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
    </div>
  );
}